### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tyson-swetnam**
There were some spacing problems in the .md that kept the formatting from rendering. 

I've made a few minor editorial changes as well.

### CODE REVIEW

**Review by julianpistorius — APPROVED** [review]
Thanks for catching that @tyson-swetnam! 🙇

**Comment by julianpistorius** [comment]
@megbalk & @bjoyce3 - Look OK?

**Comment by bjoyce3** [comment]
Looks good.

**Review by bjoyce3 — APPROVED** [review]
Looks good overall. Will need to finalize the MIssion/Vision/Values statements at some point or another.

**Comment by megbalk** [comment]
@bjoyce3 what needs to be finalized?

**Comment by bjoyce3** [comment]
@megbalk you're in charge. Merge when you think it's time. I just gave my opinion :)

**Comment by megbalk** [comment]
@bjoyce3 I guess I'm confused...is it not final?

**Pull request merged**
